### ISSUE TITLE
ローマ字の表記方法の統一

### ISSUE THREAD

**Issue by dokimiki** [AmanesCode/voicevox-snippets#2]
# 詳細
snippetsのローマ字表記で、`tsu`など`s`を含む表記(ヘボン式)と、`tu`など`s`を含まない表記が混同しているようです。
どちらかに統一した方が入力しやすくなるのではないでしょうか?

# 該当箇所

`si`
https://github.com/AmanesCode/voicevox-snippets/blob/fff860d4fe17c23b3f26ba8ec073c17f0db8531d/snippets/snippets.code-snippets#L23

https://github.com/AmanesCode/voicevox-snippets/blob/fff860d4fe17c23b3f26ba8ec073c17f0db8531d/snippets/snippets.code-snippets#L108

https://github.com/AmanesCode/voicevox-snippets/blob/fff860d4fe17c23b3f26ba8ec073c17f0db8531d/snippets/snippets.code-snippets#L133

https://github.com/AmanesCode/voicevox-snippets/blob/fff860d4fe17c23b3f26ba8ec073c17f0db8531d/snippets/snippets.code-snippets#L138

`shi`
https://github.com/AmanesCode/voicevox-snippets/blob/fff860d4fe17c23b3f26ba8ec073c17f0db8531d/snippets/snippets.code-snippets#L33

https://github.com/AmanesCode/voicevox-snippets/blob/fff860d4fe17c23b3f26ba8ec073c17f0db8531d/snippets/snippets.code-snippets#L63

`ti`
https://github.com/AmanesCode/voicevox-snippets/blob/fff860d4fe17c23b3f26ba8ec073c17f0db8531d/snippets/snippets.code-snippets#L83

https://github.com/AmanesCode/voicevox-snippets/blob/fff860d4fe17c23b3f26ba8ec073c17f0db8531d/snippets/snippets.code-snippets#L108

`tu`
https://github.com/AmanesCode/voicevox-snippets/blob/fff860d4fe17c23b3f26ba8ec073c17f0db8531d/snippets/snippets.code-snippets#L18

https://github.com/AmanesCode/voicevox-snippets/blob/fff860d4fe17c23b3f26ba8ec073c17f0db8531d/snippets/snippets.code-snippets#L43

https://github.com/AmanesCode/voicevox-snippets/blob/fff860d4fe17c23b3f26ba8ec073c17f0db8531d/snippets/snippets.code-snippets#L53

https://github.com/AmanesCode/voicevox-snippets/blob/fff860d4fe17c23b3f26ba8ec073c17f0db8531d/snippets/snippets.code-snippets#L133

https://github.com/AmanesCode/voicevox-snippets/blob/fff860d4fe17c23b3f26ba8ec073c17f0db8531d/snippets/snippets.code-snippets#L148

https://github.com/AmanesCode/voicevox-snippets/blob/fff860d4fe17c23b3f26ba8ec073c17f0db8531d/snippets/snippets.code-snippets#L153

`tsu`
https://github.com/AmanesCode/voicevox-snippets/blob/fff860d4fe17c23b3f26ba8ec073c17f0db8531d/snippets/snippets.code-snippets#L173

# 参考
ヘボン式ローマ字一覧 https://www.ezairyu.mofa.go.jp/passport/hebon.html

**Comment by AmanesCode** [comment]
>snippetsのローマ字表記で、tsuなどsを含む表記(ヘボン式)と、tuなどsを含まない表記が混同しているようです。
どちらかに統一した方が入力しやすくなるのではないでしょうか?
そうですね。siやtuなど日本語をローマ字入力する際になるべく近い状態に統一したいと思います

**Comment by AmanesCode** [comment]
>snippetsのローマ字表記で、tsuなどsを含む表記(ヘボン式)と、tuなどsを含まない表記が混同しているようです。
どちらかに統一した方が入力しやすくなるのではないでしょうか?

そうですね。tuやsiなどの予測変換先を見たときにわかりやすく打ちやすい方に統一したいと思います。
